### ISSUE TITLE
A word of thanks

### ISSUE THREAD

**Issue by algoz098** [samuelcolvin/cloudflare-proxy#1]
This is not a problem just me sayng thanks.

I placed your code for a worker of mine, and this saved me a lot of work, and problems, prob a lot of money too.

So thank you for this, really appreciate!

**Comment by samuelcolvin** [comment]
No problem at all, please it helped.

Really good of you to take the time to say thanks.

If you wish you can sponsor me on GitHub, but absolutely no obligation.
